name: build

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:

    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ubuntu-latest, macos-latest, windows-latest]
        python-version: [3.6, 3.7, 3.8]

    steps:
    - uses: actions/checkout@v2
    - name: Set up Python ${{ matrix.python-version }}
      uses: actions/setup-python@v1
      with:
        python-version: ${{ matrix.python-version }}
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt
    - name: Lint with Black
      run: |
        pip install black
        black --check --diff defe
    - name: Run Tests
      run: |
        python tests.py
    - name: Test Coverage
      run: |
        pip install codecov
        coverage run tests.py
        codecov
        bash <(curl -s https://codecov.io/bash) || echo "Codecov did not collect coverage reports"
